version: '3.3'

volumes:
  seq-data:

services:
    seq:
        container_name: seq
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
        image: 'datalust/seq:latest'
        network_mode: host
        volumes:
          - seq-data:/data